name: dart_mixpanel
description: Implementation of the mixpanel client library for flutter
homepage: https://foreverday.one
repository: https://github.com/4ed1/dart_mixpanel
issue_tracker: https://github.com/4ed1/dart_mixpanel/issues

version: 0.0.5

dependencies:
    flutter:
        sdk: flutter
    uuid: ^3.0.2
    shared_preferences: ^2.0.5
    package_info: ^2.0.0
    device_info: ^2.0.0
    http: ^0.13.0
    meta: ^1.1.6

environment:
  sdk: ">=2.0.0 <3.0.0"
